# Generated by Django 4.1.3 on 2022-11-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_options_blog_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tipo',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
